publish_url: https://localhost:3000 

dfe_signin:
  secret: please_change_me # Override with SETTINGS__DFE_SIGNIN__SECRET
  base_url: https://localhost:3000
teacher_training_api:
  secret: secret
  base_url: http://localhost:3001
search_ui:
  base_url: https://localhost:5000
environment:
  label: "Development"
  selector_name: "development"
log_level: debug

# localhost, circumvent dfe_signin
use_ssl: false
authentication:
  mode: persona     # none critical systems, ie localhost
  basic_auth:       # mainly to enforce for none critical systems
    disabled: true 
