dfe_signin:
  issuer: https://oidc.signin.education.gov.uk
  secret: please_change_me # Override with SETTINGS__DFE_SIGNIN__SECRET
  profile: https://profile.signin.education.gov.uk
  base_url: https://www.publish-teacher-training-courses.service.gov.uk
  user_search_url: https://support.signin.education.gov.uk/users
manage_backend:
  base_url: https://api2.publish-teacher-training-courses.service.gov.uk
search_ui:
  base_url: https://find-postgraduate-teacher-training.education.gov.uk
environment:
  label: "Beta"
  selector_name: "beta"
