dfe_signin:
  secret: please_change_me # Override with SETTINGS__DFE_SIGNIN__SECRET
  base_url: https://www.qa.publish-teacher-training-courses.service.gov.uk
teacher_training_api:
  base_url: https://api.qa.publish-teacher-training-courses.service.gov.uk
search_ui:
  base_url: https://www.qa.find-postgraduate-teacher-training.service.gov.uk
environment:
  label: "QA"
  selector_name: "qa"
basic_auth: true
developer_auth: true
