publish_url: https://sandbox.publish-teacher-training-courses.service.gov.uk

dfe_signin:
  issuer: https://oidc.signin.education.gov.uk
  secret: please_change_me # Override with SETTINGS__DFE_SIGNIN__SECRET
  profile: https://profile.signin.education.gov.uk
  base_url: https://sandbox.publish-teacher-training-courses.service.gov.uk
  user_search_url: https://support.signin.education.gov.uk/users
teacher_training_api:
  base_url: https://sandbox.api.publish-teacher-training-courses.service.gov.uk
search_ui:
  base_url: https://sandbox.find-postgraduate-teacher-training.service.gov.uk
environment:
  label: "Sandbox"
  selector_name: "sandbox"
authentication:
  mode: dfe_signin
