dfe_signin:
  issuer: https://pp-oidc.signin.education.gov.uk
  profile: https://pp-profile.signin.education.gov.uk
  secret: please_change_me # Override with SETTINGS__DFE_SIGNIN__SECRET
  base_url: https://www.staging.publish-teacher-training-courses.service.gov.uk
  user_search_url: https://pp-support.signin.education.gov.uk/users
manage_backend:
  base_url: https://api.staging.publish-teacher-training-courses.service.gov.uk
search_ui:
  base_url: https://www.staging.find-postgraduate-teacher-training.service.gov.uk
environment:
  label: "Staging"
  selector_name: "staging"
basic_auth: true
developer_auth: true
