name: Smoke Tests
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to run tests against (qa, staging, production or sandbox)'
        required: true
      pr:
        description: 'The PR number if the environment is review'
        required: false        

jobs:
  smoke_tests:
    name: smoke-tests-${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.7.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: install bundler and gems
        run: |
          gem install bundler
          echo 'gem "httparty"' >> Gemfile
          echo 'gem "rspec"' >> Gemfile
          bundle

      - uses: softprops/turnstyle@v1
        name: Wait for other runs
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_API_ACCESS_TOKEN }}

      - name: Set Environment variables
        run: |
          if [ ! -z "${{ github.event.inputs.pr }}" ]; then 
            PR_NUMBER=${{ github.event.inputs.pr }}
            echo "publish_url: https://publish-teacher-training-pr-$PR_NUMBER.london.cloudapps.digital" >> config/settings/review.yml
          fi;

      - name: Smoke Tests ${{ github.event.inputs.environment }}
        run: RAILS_ENV=${{ github.event.inputs.environment }} ./bin/bundle exec rspec spec/smoke --options ./.rspec_smoke

      - name: 'Notify #twd_publish_register_tech on failure'
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: twd_publish_register_tech
          SLACK_COLOR: '#ef5343'
          SLACK_ICON_EMOJI: ':github-logo:'
          SLACK_USERNAME: Publish Teacher Training
          SLACK_TITLE: Smoke tests failure
          SLACK_MESSAGE: ':alert: <!channel> Smoke tests failure on ${{ github.event.inputs.environment }} :fire:'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
